-- ============================================================
-- Carrot Market Clone — Supabase schema
-- target project : goms_projects (zfcbskhjyadsuylxifhm)
-- naming         : 모든 객체에 carrot_ 접두사 (기존 테이블과 충돌 회피)
-- auth           : Supabase Auth (auth.users) 사용 — public.users(커스텀)는 건드리지 않음
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 1) carrot_profiles  — auth.users 1:1
-- ────────────────────────────────────────────────────────────
create table if not exists public.carrot_profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  email       text not null,
  nickname    text not null,
  region      text not null default '',
  avatar_url  text,
  created_at  timestamptz not null default now()
);

alter table public.carrot_profiles enable row level security;

drop policy if exists "carrot_profiles_select_all"   on public.carrot_profiles;
drop policy if exists "carrot_profiles_insert_self"  on public.carrot_profiles;
drop policy if exists "carrot_profiles_update_self"  on public.carrot_profiles;

create policy "carrot_profiles_select_all"
  on public.carrot_profiles for select using (true);

create policy "carrot_profiles_insert_self"
  on public.carrot_profiles for insert with check (auth.uid() = id);

create policy "carrot_profiles_update_self"
  on public.carrot_profiles for update using (auth.uid() = id);

-- 회원가입 시 자동으로 carrot_profiles row 생성
create or replace function public.handle_new_carrot_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.carrot_profiles (id, email, nickname, region)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'nickname', split_part(coalesce(new.email,''), '@', 1)),
    coalesce(new.raw_user_meta_data->>'region', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_carrot on auth.users;
create trigger on_auth_user_created_carrot
  after insert on auth.users
  for each row execute function public.handle_new_carrot_user();

-- ────────────────────────────────────────────────────────────
-- 2) carrot_products
-- ────────────────────────────────────────────────────────────
create table if not exists public.carrot_products (
  id           bigint generated by default as identity primary key,
  seller_id    uuid not null references auth.users(id) on delete cascade,
  title        text not null,
  price        bigint not null default 0,
  description  text not null default '',
  category     text not null default '기타',
  status       text not null default 'on_sale'
                 check (status in ('on_sale','reserved','sold')),
  region       text not null default '',
  images       text[] not null default '{}',
  created_at   timestamptz not null default now()
);

create index if not exists idx_carrot_products_created on public.carrot_products(created_at desc);
create index if not exists idx_carrot_products_region  on public.carrot_products(region);
create index if not exists idx_carrot_products_seller  on public.carrot_products(seller_id);
create index if not exists idx_carrot_products_status  on public.carrot_products(status);

alter table public.carrot_products enable row level security;

drop policy if exists "carrot_products_select_all"     on public.carrot_products;
drop policy if exists "carrot_products_insert_seller"  on public.carrot_products;
drop policy if exists "carrot_products_update_seller"  on public.carrot_products;
drop policy if exists "carrot_products_delete_seller"  on public.carrot_products;

create policy "carrot_products_select_all"
  on public.carrot_products for select using (true);

create policy "carrot_products_insert_seller"
  on public.carrot_products for insert with check (auth.uid() = seller_id);

create policy "carrot_products_update_seller"
  on public.carrot_products for update using (auth.uid() = seller_id);

create policy "carrot_products_delete_seller"
  on public.carrot_products for delete using (auth.uid() = seller_id);

-- ────────────────────────────────────────────────────────────
-- 3) carrot_favorites  (관심)
-- ────────────────────────────────────────────────────────────
create table if not exists public.carrot_favorites (
  user_id     uuid not null references auth.users(id) on delete cascade,
  product_id  bigint not null references public.carrot_products(id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (user_id, product_id)
);

create index if not exists idx_carrot_favorites_product on public.carrot_favorites(product_id);

alter table public.carrot_favorites enable row level security;

drop policy if exists "carrot_favorites_select_self" on public.carrot_favorites;
drop policy if exists "carrot_favorites_insert_self" on public.carrot_favorites;
drop policy if exists "carrot_favorites_delete_self" on public.carrot_favorites;

create policy "carrot_favorites_select_self"
  on public.carrot_favorites for select using (auth.uid() = user_id);

create policy "carrot_favorites_insert_self"
  on public.carrot_favorites for insert with check (auth.uid() = user_id);

create policy "carrot_favorites_delete_self"
  on public.carrot_favorites for delete using (auth.uid() = user_id);

-- ────────────────────────────────────────────────────────────
-- 4) carrot_chat_rooms  (1:1 buyer ↔ seller)
-- ────────────────────────────────────────────────────────────
create table if not exists public.carrot_chat_rooms (
  id          bigint generated by default as identity primary key,
  product_id  bigint not null references public.carrot_products(id) on delete cascade,
  buyer_id    uuid not null references auth.users(id) on delete cascade,
  seller_id   uuid not null references auth.users(id) on delete cascade,
  created_at  timestamptz not null default now(),
  unique (product_id, buyer_id),
  check (buyer_id <> seller_id)
);

create index if not exists idx_carrot_chat_rooms_buyer  on public.carrot_chat_rooms(buyer_id);
create index if not exists idx_carrot_chat_rooms_seller on public.carrot_chat_rooms(seller_id);

alter table public.carrot_chat_rooms enable row level security;

drop policy if exists "carrot_chat_rooms_select_member" on public.carrot_chat_rooms;
drop policy if exists "carrot_chat_rooms_insert_buyer"  on public.carrot_chat_rooms;

create policy "carrot_chat_rooms_select_member"
  on public.carrot_chat_rooms for select
  using (auth.uid() = buyer_id or auth.uid() = seller_id);

create policy "carrot_chat_rooms_insert_buyer"
  on public.carrot_chat_rooms for insert
  with check (
    auth.uid() = buyer_id
    and exists (
      select 1 from public.carrot_products p
      where p.id = product_id and p.seller_id = carrot_chat_rooms.seller_id
    )
  );

-- ────────────────────────────────────────────────────────────
-- 5) carrot_chat_messages
-- ────────────────────────────────────────────────────────────
create table if not exists public.carrot_chat_messages (
  id          bigint generated by default as identity primary key,
  room_id     bigint not null references public.carrot_chat_rooms(id) on delete cascade,
  sender_id   uuid not null references auth.users(id) on delete cascade,
  text        text not null check (length(text) between 1 and 2000),
  created_at  timestamptz not null default now()
);

create index if not exists idx_carrot_chat_messages_room on public.carrot_chat_messages(room_id, id);

alter table public.carrot_chat_messages enable row level security;

drop policy if exists "carrot_chat_messages_select_member" on public.carrot_chat_messages;
drop policy if exists "carrot_chat_messages_insert_member" on public.carrot_chat_messages;

create policy "carrot_chat_messages_select_member"
  on public.carrot_chat_messages for select
  using (
    exists (
      select 1 from public.carrot_chat_rooms r
      where r.id = room_id
        and (r.buyer_id = auth.uid() or r.seller_id = auth.uid())
    )
  );

create policy "carrot_chat_messages_insert_member"
  on public.carrot_chat_messages for insert
  with check (
    auth.uid() = sender_id
    and exists (
      select 1 from public.carrot_chat_rooms r
      where r.id = room_id
        and (r.buyer_id = auth.uid() or r.seller_id = auth.uid())
    )
  );

-- ────────────────────────────────────────────────────────────
-- 6) Realtime 활성화 — chat_messages 변경을 클라이언트가 구독
-- ────────────────────────────────────────────────────────────
do $$
begin
  -- 이미 추가되어 있으면 에러나므로 try/catch
  begin
    alter publication supabase_realtime add table public.carrot_chat_messages;
  exception when duplicate_object then
    null;
  end;
end$$;

-- ────────────────────────────────────────────────────────────
-- 7) Storage — carrot-products 버킷 + 정책
--    (대시보드 Storage 페이지에서 만들거나 아래 SQL로 한번에)
-- ────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public)
values ('carrot-products', 'carrot-products', true)
on conflict (id) do nothing;

drop policy if exists "carrot_storage_public_read"   on storage.objects;
drop policy if exists "carrot_storage_auth_insert"   on storage.objects;
drop policy if exists "carrot_storage_owner_delete"  on storage.objects;

create policy "carrot_storage_public_read"
  on storage.objects for select to public
  using (bucket_id = 'carrot-products');

-- 업로드는 본인 폴더(`{auth.uid()}/...`)에만 허용
create policy "carrot_storage_auth_insert"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'carrot-products'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "carrot_storage_owner_delete"
  on storage.objects for delete to authenticated
  using (bucket_id = 'carrot-products' and owner = auth.uid());

-- ────────────────────────────────────────────────────────────
-- 검증
-- ────────────────────────────────────────────────────────────
select t.tablename,
       case when t.rowsecurity then 'ON' else 'OFF' end as rls,
       (select count(*) from pg_policies p
          where p.schemaname='public' and p.tablename=t.tablename) as policies
from pg_tables t
where t.schemaname = 'public'
  and t.tablename like 'carrot_%'
order by t.tablename;
